services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - DATABASE_URL=${DATABASE_URL}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.financialapp.rule=Host(`stockumkm-financialapp-nime9u-a80ff3-34-50-98-189.sslip.io`)"
      - "traefik.http.routers.financialapp.entrypoints=web" # Atau websecure jika pakai HTTPS
      - "traefik.http.services.financialapp.loadbalancer.server.port=3000"

networks:
  dokploy-network:
    external: true
